// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvyVmr1s3AhAAq42oJMbrxZl8Cw3pgudk',
    appId: '1:544496078056:web:53279611fc94a47e0e4d5d',
    messagingSenderId: '544496078056',
    projectId: 'ta-apartment',
    authDomain: 'ta-apartment.firebaseapp.com',
    storageBucket: 'ta-apartment.firebasestorage.app',
    measurementId: 'G-58Z3EF0LVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCah1WKgYWw4lJX6m0VdNjk7nuIQhWQp9w',
    appId: '1:544496078056:android:413ac517f5ed70330e4d5d',
    messagingSenderId: '544496078056',
    projectId: 'ta-apartment',
    storageBucket: 'ta-apartment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQVhbepkcnB1R5epmS3No7vNgvzI5P8o4',
    appId: '1:544496078056:ios:afe0cb71528742a10e4d5d',
    messagingSenderId: '544496078056',
    projectId: 'ta-apartment',
    storageBucket: 'ta-apartment.firebasestorage.app',
    iosBundleId: 'com.example.myApart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQVhbepkcnB1R5epmS3No7vNgvzI5P8o4',
    appId: '1:544496078056:ios:afe0cb71528742a10e4d5d',
    messagingSenderId: '544496078056',
    projectId: 'ta-apartment',
    storageBucket: 'ta-apartment.firebasestorage.app',
    iosBundleId: 'com.example.myApart',
  );
}
